# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a7a217b6189c68154c3e813d75667bf95634aeafe889cb7295439a18bb413546aca3bf35f0cb509c51a5b842be8ecf83b8215a14e78b28edaae895e197043d

test:
  secret_key_base: 32e1d122c6142a34288c7d5f40177cdced6622bd481fb1c413d8a6443ca131832319418c5f4f553251ae3acf86811f804339cb1e552bb85ad133761563c6e1fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
